In [ ]:
# Team members: Zhilin Zhai(ZZL), Yining Liang (YNL), Yiren Shen(YRS)

In [ ]:
# Introduction: (zzl)(ynl)(yrs)
#  In this project, we are going to help Alex to find the suitable colleges by four factors which are "safety","urban"" diversity" and "quality".
#  Firstly, we clean the dataset by dropping all of the empty blank in Excel. 
#  Secondly,We define the safety city by comparing the each crime rate to the mean value in the "crime_2015". We believe that the urban area with the lower crime rate could satisfy Alex's requirment. 
#  Thirdly, we define the college quanlity by three elements which are "ADM_RATE_ALL" "ACTCM25" and "TUITIONFEE_OUT". We belive that the higher quality colleges should satisfy Alex requirment by lower admission rate, higher Act mid score and higher tuition.
#  In the end, we define the college diversity from the "college_data". We believe that any colleges with zero diverse race can not satisfy Alex's requirment.

In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv('Downloads/Crime_2015.csv')

In [37]:
df

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
0,"Abilene, TX M.S.A.",412.5,5.3,56.0,78.4,272.8,"3,609.00",852,"2,493.60",263.4,TX,Abilene
1,"Akron, OH M.S.A.",238.4,5.1,38.2,75.2,119.8,"2,552.40",575.3,"1,853.00",124.1,OH,Akron
2,"Albany, GA M.S.A.",667.9,7.8,30.4,157.9,471.8,"3,894.10","1,099.60","2,652.80",141.7,GA,Albany
3,"Albany, OR M.S.A.",114.3,2.5,28.2,20.7,63.0,"3,208.40",484.6,"2,476.10",247.7,OR,Albany
4,"Albuquerque, NM M.S.A.",792.6,6.1,63.8,206.7,516.0,"4,607.80",883.4,"3,047.60",676.9,NM,Albuquerque
...,...,...,...,...,...,...,...,...,...,...,...,...
373,"Guayama, Puerto Rico M.S.A.",251.6,11.4,6.3,74.6,159.3,823.2,265.5,531.1,26.6,"Guayama, Puerto Rico M.S.A.",Guayama
374,"Mayaguez, Puerto Rico M.S.A.",237.5,11.5,5.2,82.3,138.6,"1,320.00",377.1,861.6,81.3,"Mayaguez, Puerto Rico M.S.A.",Mayaguez
375,"Ponce, Puerto Rico M.S.A.",231.4,18.0,5.0,66.2,142.2,885,214.4,632.4,38.1,"Ponce, Puerto Rico M.S.A.",Ponce
376,"San German, Puerto Rico M.S.A.",92.1,5.4,4.6,16.1,66.0,420,168.9,226.5,24.6,"San German, Puerto Rico M.S.A.",San German
377,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",262,20.6,4.9,157.8,78.7,"1,281.20",281.8,835,164.3,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",San Juan

In [38]:
df.describe(include='all') #(zzl)
# We are not able to calculate the mean, std, min in the data set since there are lots of blank cell in Excel, also the comma. Python not able to read the data with comma.

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
count,378,377,378.000000,378.000000,378.000000,377.000000,372,374,375,378.000000,378,373
unique,378,368,NaN,NaN,NaN,NaN,369,365,369,NaN,58,341
top,"Greensboro-High Point, NC M.S.A.",324.1,NaN,NaN,NaN,NaN,"3,019.10",517.6,"1,631.70",NaN,CA,Springfield
freq,1,2,NaN,NaN,NaN,NaN,2,2,3,NaN,31,4
mean,NaN,NaN,4.574868,41.306614,77.702646,241.319098,NaN,NaN,NaN,191.081746,NaN,NaN
std,NaN,NaN,3.383652,19.506386,53.977181,137.267225,NaN,NaN,NaN,134.532918,NaN,NaN
min,NaN,NaN,0.000000,2.700000,2.300000,25.500000,NaN,NaN,NaN,15.700000,NaN,NaN
25%,NaN,NaN,2.200000,29.000000,36.625000,144.200000,NaN,NaN,NaN,97.550000,NaN,NaN
50%,NaN,NaN,3.800000,37.550000,67.350000,215.700000,NaN,NaN,NaN,154.450000,NaN,NaN
75%,NaN,NaN,6.275000,51.550000,106.050000,304.900000,NaN,NaN,NaN,249.650000,NaN,NaN
max,NaN,NaN,20.600000,165.600000,351.900000,981.300000,NaN,NaN,NaN,718.600000,NaN,NaN

In [39]:
df['ViolentCrime'].describe() 
# (zzl)

count       377
unique      368
top       324.1
freq          2
Name: ViolentCrime, dtype: object

In [40]:
null_count = df.isnull().sum()
null_count
# we count all the zero in Excel and drop them (zzl)

MSA                  0
ViolentCrime         1
Murder               0
Rape                 0
Robbery              0
AggravatedAssault    1
PropertyCrime        6
Burglary             4
Theft                3
MotorVehicleTheft    0
State                0
City                 5
dtype: int64

In [41]:
df['ViolentCrime'] = df['ViolentCrime'].str.replace(',','')
df['PropertyCrime'] = df['PropertyCrime'].str.replace(',','')
df['Burglary'] = df['Burglary'].str.replace(',','')
df['Theft'] = df['Theft'].str.replace(',','') 
# we search the code from Google (zzl)
# we replace the replace the comma in the dataset to empty (this step only can use when the element are string) we have to redefine the string into float in the next step.

In [42]:
df['ViolentCrime']=df['ViolentCrime'].astype(float)
df['PropertyCrime']=df['PropertyCrime'].astype(float)
df['Burglary']=df['Burglary'].astype(float)
df['Theft']=df['Theft'].astype(float)
# we search the code from Google (zzl)
# In order to calculate out the mean, we redefine the the element into float

In [43]:
crime_data=df

In [44]:
crime_data.describe(include='all')
# We calculate out the mean of each elements (zzl)

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
count,378,377.000000,378.000000,378.000000,378.000000,377.000000,372.000000,374.000000,375.000000,378.000000,378,373
unique,378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,341
top,"Greensboro-High Point, NC M.S.A.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CA,Springfield
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,4
mean,NaN,364.988064,4.574868,41.306614,77.702646,241.319098,2621.934409,537.622193,1900.392800,191.081746,NaN,NaN
std,NaN,181.214645,3.383652,19.506386,53.977181,137.267225,820.691755,229.176000,576.696896,134.532918,NaN,NaN
min,NaN,61.600000,0.000000,2.700000,2.300000,25.500000,420.000000,159.700000,226.500000,15.700000,NaN,NaN
25%,NaN,236.300000,2.200000,29.000000,36.625000,144.200000,2022.100000,362.725000,1493.900000,97.550000,NaN,NaN
50%,NaN,333.700000,3.800000,37.550000,67.350000,215.700000,2585.250000,503.350000,1854.000000,154.450000,NaN,NaN
75%,NaN,447.700000,6.275000,51.550000,106.050000,304.900000,3207.950000,671.050000,2264.050000,249.650000,NaN,NaN
max,NaN,1160.000000,20.600000,165.600000,351.900000,981.300000,5190.600000,1503.700000,3936.400000,718.600000,NaN,NaN

In [45]:
crime_data_mask =(crime_data['ViolentCrime']<= crime_data['ViolentCrime'].mean())&(crime_data['PropertyCrime'] <= crime_data['PropertyCrime'].mean())&(crime_data['Burglary'] <= crime_data['Burglary'].mean())&(crime_data['Theft'] <= crime_data['Theft'].mean())&(crime_data['MotorVehicleTheft'] <= crime_data['MotorVehicleTheft'].mean())
crime_data[crime_data_mask] 
# we filter out the cities which have the lower crime rate by comparing the factors of  "violent crime""property crime" "burglary""Theft""Motervehicle theft" with their mean.
# (zzl)

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
6,"Altoona, PA M.S.A.",216.5,0.8,28.7,25.5,161.6,1430.2,218.9,1163.6,47.8,PA,Altoona
8,"Ames, IA M.S.A.",158.5,1.0,47.2,19.9,90.3,1848.3,311.7,1462.0,74.5,IA,Ames
10,"Ann Arbor, MI M.S.A.",319.5,1.9,57.0,51.4,209.2,1791.9,290.4,1417.4,84.2,MI,Ann Arbor
12,"Appleton, WI M.S.A.",138.8,0.4,24.1,8.6,105.7,1394.9,206.6,1154.7,33.5,WI,Appleton
20,"Bangor, ME M.S.A.",67.3,2.0,9.1,17.6,38.5,1984.5,337.0,1604.4,43.1,ME,Bangor
...,...,...,...,...,...,...,...,...,...,...,...,...
373,"Guayama, Puerto Rico M.S.A.",251.6,11.4,6.3,74.6,159.3,823.2,265.5,531.1,26.6,"Guayama, Puerto Rico M.S.A.",Guayama
374,"Mayaguez, Puerto Rico M.S.A.",237.5,11.5,5.2,82.3,138.6,1320.0,377.1,861.6,81.3,"Mayaguez, Puerto Rico M.S.A.",Mayaguez
375,"Ponce, Puerto Rico M.S.A.",231.4,18.0,5.0,66.2,142.2,885.0,214.4,632.4,38.1,"Ponce, Puerto Rico M.S.A.",Ponce
376,"San German, Puerto Rico M.S.A.",92.1,5.4,4.6,16.1,66.0,420.0,168.9,226.5,24.6,"San German, Puerto Rico M.S.A.",San German
377,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",262.0,20.6,4.9,157.8,78.7,1281.2,281.8,835.0,164.3,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",San Juan

In [46]:
df=pd.read_csv('Downloads/CollegeScorecard2.csv')
# we create a new Exel by manually set out the elements (ADM_RATE_ALL,ACTCM25,TUITIONFEE_OUT,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN)
# we manully combine the elements with city (zzl, ynl,yrs)

In [47]:
df.isnull().sum()
# we drop the zero in the new Excel (collegescorecard2)

INSTNM               0
ADM_RATE_ALL      5320
ACTCM25           6462
TUITIONFEE_OUT    3608
UGDS_WHITE         714
UGDS_BLACK         714
UGDS_HISP          714
UGDS_ASIAN         714
UGDS_AIAN          714
UGDS_NHPI          714
UGDS_2MOR          714
UGDS_NRA           714
UGDS_UNKN          714
City                 0
dtype: int64

In [48]:
df.describe(include='all')#(zzl)

,INSTNM,ADM_RATE_ALL,ACTCM25,TUITIONFEE_OUT,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,City
count,7804,2484.000000,1342.000000,4196.000000,7090.000000,7090.000000,7090.000000,7090.000000,7090.000000,7090.000000,7090.000000,7090.000000,7090.000000,7804
unique,7634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2545
top,Marinello School of Beauty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New York
freq,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92
mean,NaN,0.690568,20.365127,16359.024786,0.517627,0.187396,0.156616,0.032687,0.013845,0.004477,0.022208,0.014668,0.049347,NaN
std,NaN,0.203374,3.528206,9869.967465,0.287820,0.222093,0.220044,0.072945,0.068960,0.031660,0.032101,0.045759,0.101506,NaN
min,NaN,0.000000,1.000000,80.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,0.561975,18.000000,8800.000000,0.279425,0.035100,0.025600,0.002300,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
50%,NaN,0.716700,20.000000,14339.000000,0.565150,0.099250,0.068500,0.012000,0.002700,0.000000,0.015500,0.000000,0.014600,NaN
75%,NaN,0.838800,22.000000,20597.000000,0.759600,0.254575,0.187300,0.031100,0.007400,0.002400,0.030900,0.010100,0.048300,NaN
max,NaN,1.000000,33.000000,64900.000000,1.000000,1.000000,1.000000,0.971800,1.000000,1.000000,1.000000,0.902400,1.000000,NaN

In [49]:
college_data=df

In [50]:
college_data_mask=(college_data['ADM_RATE_ALL']<= college_data['ADM_RATE_ALL'].mean())&(college_data['ACTCM25']>= college_data['ACTCM25'].mean())
# we filter out the colleges which ADM_RATE_ALL is lower than mean,ACTCM25 is higher than mean (zzl)(yrs)

In [51]:
college_data[college_data_mask]

,INSTNM,ADM_RATE_ALL,ACTCM25,TUITIONFEE_OUT,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,City
5,The University of Alabama,0.5655,22.0,23950.0,0.7865,0.1140,0.0313,0.0112,0.0044,0.0011,0.0210,0.0278,0.0028,Tuscaloosa
10,Birmingham Southern College,0.6422,23.0,30690.0,0.8103,0.0940,0.0305,0.0390,0.0102,0.0000,0.0076,0.0000,0.0085,Birmingham
51,Spring Hill College,0.4627,21.0,30924.0,0.6643,0.1608,0.0875,0.0071,0.0063,0.0000,0.0236,0.0134,0.0370,Mobile
139,Lyon College,0.5898,22.0,23594.0,0.7737,0.0421,0.0509,0.0123,0.0193,0.0000,0.0000,0.0298,0.0719,Batesville
142,University of Arkansas,0.5858,23.0,19074.0,0.7874,0.0492,0.0644,0.0237,0.0120,0.0007,0.0321,0.0276,0.0028,Fayetteville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5588,Franklin W Olin College of Engineering,0.1685,31.0,45156.0,0.5335,0.0087,0.0408,0.1720,0.0029,0.0000,0.0612,0.0671,0.1137,Needham
5665,DigiPen Institute of Technology,0.6635,25.0,26720.0,0.4799,0.0089,0.0638,0.0570,0.0011,0.0045,0.0481,0.1040,0.2327,Redmond
6029,University of South Florida-St Petersburg,0.4499,21.0,16736.0,0.6903,0.0721,0.1464,0.0407,0.0018,0.0035,0.0286,0.0025,0.0142,St. Petersburg
6233,University of South Florida-Sarasota-Manatee,0.4499,22.0,16502.0,0.7373,0.0652,0.1323,0.0245,0.0024,0.0012,0.0174,0.0024,0.0174,Sarasota
6498,University of Minnesota-Rochester,0.4455,23.0,13056.0,0.7966,0.0692,0.0314,0.0566,0.0000,0.0000,0.0314,0.0042,0.0105,Rochester

In [52]:
crime_data[crime_data_mask].to_csv('crime_data.csv',index=False,header=True) #in order to save this data for further use, we tranfered it to csv format, and named it "crime_data" (ynl)

In [53]:
df = pd.read_csv('crime_data.csv') #we wanted to read the "crime_data" and checked if it is the list we needed/expected. (ynl,yrs)

In [54]:
df

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
0,"Altoona, PA M.S.A.",216.5,0.8,28.7,25.5,161.6,1430.2,218.9,1163.6,47.8,PA,Altoona
1,"Ames, IA M.S.A.",158.5,1.0,47.2,19.9,90.3,1848.3,311.7,1462.0,74.5,IA,Ames
2,"Ann Arbor, MI M.S.A.",319.5,1.9,57.0,51.4,209.2,1791.9,290.4,1417.4,84.2,MI,Ann Arbor
3,"Appleton, WI M.S.A.",138.8,0.4,24.1,8.6,105.7,1394.9,206.6,1154.7,33.5,WI,Appleton
4,"Bangor, ME M.S.A.",67.3,2.0,9.1,17.6,38.5,1984.5,337.0,1604.4,43.1,ME,Bangor
...,...,...,...,...,...,...,...,...,...,...,...,...
113,"Guayama, Puerto Rico M.S.A.",251.6,11.4,6.3,74.6,159.3,823.2,265.5,531.1,26.6,"Guayama, Puerto Rico M.S.A.",Guayama
114,"Mayaguez, Puerto Rico M.S.A.",237.5,11.5,5.2,82.3,138.6,1320.0,377.1,861.6,81.3,"Mayaguez, Puerto Rico M.S.A.",Mayaguez
115,"Ponce, Puerto Rico M.S.A.",231.4,18.0,5.0,66.2,142.2,885.0,214.4,632.4,38.1,"Ponce, Puerto Rico M.S.A.",Ponce
116,"San German, Puerto Rico M.S.A.",92.1,5.4,4.6,16.1,66.0,420.0,168.9,226.5,24.6,"San German, Puerto Rico M.S.A.",San German
117,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",262.0,20.6,4.9,157.8,78.7,1281.2,281.8,835.0,164.3,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",San Juan

In [55]:
college_data[college_data_mask].to_csv('college_data.csv',index=False,header=True) #in order to save this data for further use, we tranfered it to csv format, and named it "college_data" (ynl)

In [56]:
df = pd.read_csv('college_data.csv') #we wanted to read the "college_data" and checked if it is the list we needed/expected. (ynl,yrs)

In [57]:
df

,INSTNM,ADM_RATE_ALL,ACTCM25,TUITIONFEE_OUT,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,City
0,The University of Alabama,0.5655,22.0,23950.0,0.7865,0.1140,0.0313,0.0112,0.0044,0.0011,0.0210,0.0278,0.0028,Tuscaloosa
1,Birmingham Southern College,0.6422,23.0,30690.0,0.8103,0.0940,0.0305,0.0390,0.0102,0.0000,0.0076,0.0000,0.0085,Birmingham
2,Spring Hill College,0.4627,21.0,30924.0,0.6643,0.1608,0.0875,0.0071,0.0063,0.0000,0.0236,0.0134,0.0370,Mobile
3,Lyon College,0.5898,22.0,23594.0,0.7737,0.0421,0.0509,0.0123,0.0193,0.0000,0.0000,0.0298,0.0719,Batesville
4,University of Arkansas,0.5858,23.0,19074.0,0.7874,0.0492,0.0644,0.0237,0.0120,0.0007,0.0321,0.0276,0.0028,Fayetteville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,Franklin W Olin College of Engineering,0.1685,31.0,45156.0,0.5335,0.0087,0.0408,0.1720,0.0029,0.0000,0.0612,0.0671,0.1137,Needham
342,DigiPen Institute of Technology,0.6635,25.0,26720.0,0.4799,0.0089,0.0638,0.0570,0.0011,0.0045,0.0481,0.1040,0.2327,Redmond
343,University of South Florida-St Petersburg,0.4499,21.0,16736.0,0.6903,0.0721,0.1464,0.0407,0.0018,0.0035,0.0286,0.0025,0.0142,St. Petersburg
344,University of South Florida-Sarasota-Manatee,0.4499,22.0,16502.0,0.7373,0.0652,0.1323,0.0245,0.0024,0.0012,0.0174,0.0024,0.0174,Sarasota
345,University of Minnesota-Rochester,0.4455,23.0,13056.0,0.7966,0.0692,0.0314,0.0566,0.0000,0.0000,0.0314,0.0042,0.0105,Rochester

In [2]:
import csv
f = open('college_data.csv') #open "college_data" file
csv_f = csv.reader(f)#can read this data in python (read this page)

for row in csv_f: #for loop, list/print out every single column in this file.
    print(row) #print it out and see if it is the right one we expected. 
#(ynl)

['INSTNM', 'ADM_RATE_ALL', 'ACTCM25', 'TUITIONFEE_OUT', 'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'City']
['The University of Alabama', '0.5655', '22.0', '23950.0', '0.7865', '0.114', '0.0313', '0.0112', '0.0044', '0.0011', '0.021', '0.0278', '0.0028', 'Tuscaloosa']
['Birmingham Southern College', '0.6422', '23.0', '30690.0', '0.8103', '0.094', '0.0305', '0.039', '0.0102', '0.0', '0.0076', '0.0', '0.0085', 'Birmingham']
['Spring Hill College', '0.4627', '21.0', '30924.0', '0.6643', '0.1608', '0.0875', '0.0071', '0.0063', '0.0', '0.0236', '0.0134', '0.037', 'Mobile']
['Lyon College', '0.5898', '22.0', '23594.0', '0.7737', '0.0421', '0.0509', '0.0123', '0.0193', '0.0', '0.0', '0.0298', '0.0719', 'Batesville']
['University of Arkansas', '0.5858', '23.0', '19074.0', '0.7874', '0.0492', '0.0644', '0.0237', '0.012', '0.0007', '0.0321', '0.0276', '0.0028', 'Fayetteville']
['California Institute of Technology', '0.1055', '33.0', '41538.0', '0.304', '0.0174', '0.1003', '0.4248', '0.0031', '0.0', '0.0594', '0.089', '0.002', 'Pasadena']
['California Lutheran University', '0.4802', '22.0', '35720.0', '0.5232', '0.0427', '0.2523', '0.0642', '0.0135', '0.0087', '0.0173', '0.0382', '0.0399', 'Thousand Oaks']
['California Polytechnic State University-San Luis Obispo', '0.3123', '25.0', '19884.0', '0.5956', '0.0076', '0.1489', '0.1134', '0.0024', '0.0027', '0.0672', '0.0128', '0.0496', 'San Luis Obispo']
['University of California-Berkeley', '0.18', '27.0', '35742.0', '0.2857', '0.0221', '0.132', '0.3494', '0.0012', '0.0028', '0.0453', '0.1313', '0.0304', 'Berkeley']
['University of California-Davis', '0.4521', '23.0', '36773.0', '0.3125', '0.0211', '0.172', '0.3551', '0.002', '0.0048', '0.0511', '0.0618', '0.0196', 'Davis']
['University of California-Irvine', '0.4239', '21.0', '36027.0', '0.1739', '0.0187', '0.2171', '0.4371', '0.0016', '0.0042', '0.0396', '0.0894', '0.0184', 'Irvine']
['University of California-Los Angeles', '0.2199', '25.0', '35575.0', '0.2859', '0.0261', '0.1842', '0.3099', '0.0012', '0.0036', '0.0482', '0.1176', '0.0234', 'Los Angeles']
['University of California-San Diego', '0.375', '25.0', '36149.0', '0.2357', '0.0119', '0.1581', '0.4011', '0.0013', '0.0041', '0.0476', '0.1181', '0.0222', 'La Jolla']
['University of California-Santa Barbara', '0.4444', '24.0', '36624.0', '0.3965', '0.0213', '0.2481', '0.1763', '0.001', '0.0007', '0.0843', '0.0397', '0.032', 'Santa Barbara']
['Chapman University', '0.4471', '24.0', '43573.0', '0.5978', '0.0162', '0.1433', '0.0981', '0.003', '0.0024', '0.0586', '0.038', '0.0426', 'Orange']
['Claremont McKenna College', '0.1173', '29.0', '45625.0', '0.4386', '0.0397', '0.1121', '0.1083', '0.0', '0.0015', '0.0778', '0.1442', '0.0778', 'Claremont']
['Harvey Mudd College', '0.1817', '32.0', '46509.0', '0.4745', '0.0125', '0.0909', '0.2217', '0.0025', '0.0', '0.0399', '0.1096', '0.0486', 'Claremont']
["The Master's College and Seminary", '0.6137', '22.0', '28800.0', '0.6313', '0.0378', '0.1106', '0.0621', '0.0045', '0.0063', '0.0567', '0.0414', '0.0495', 'Santa Clarita']
['Loyola Marymount University', '0.5412', '25.0', '40265.0', '0.4894', '0.0563', '0.221', '0.1045', '0.0025', '0.0013', '0.0726', '0.0524', '0.0', 'Los Angeles']
['Mills College', '0.6798', '23.0', '41494.0', '0.4702', '0.0595', '0.2248', '0.1181', '0.0051', '0.0062', '0.0903', '0.0144', '0.0113', 'Oakland']
['Occidental College', '0.4239', '27.0', '46652.0', '0.515', '0.0447', '0.158', '0.1285', '0.0024', '0.0019', '0.0909', '0.0371', '0.0214', 'Los Angeles']
['Point Loma Nazarene University', '0.6654', '23.0', '30356.0', '0.6433', '0.0252', '0.195', '0.0558', '0.013', '0.0059', '0.0507', '0.0016', '0.0094', 'San Diego']
['Pomona College', '0.1392', '31.0', '43580.0', '0.448', '0.0599', '0.1474', '0.1216', '0.0006', '0.0', '0.0725', '0.0699', '0.08', 'Claremont']
['University of Redlands', '0.672', '23.0', '41290.0', '0.5061', '0.0459', '0.2605', '0.0511', '0.0055', '0.0061', '0.0373', '0.0069', '0.0806', 'Redlands']
['San Diego State University', '0.3133', '21.0', '17926.0', '0.3719', '0.0384', '0.2946', '0.14', '0.0027', '0.0035', '0.0599', '0.0409', '0.0482', 'San Diego']
['University of San Diego', '0.4885', '25.0', '41392.0', '0.5539', '0.0278', '0.1888', '0.0592', '0.0047', '0.0031', '0.0574', '0.0599', '0.0452', 'San Diego']
['University of San Francisco', '0.6129', '23.0', '40294.0', '0.311', '0.0293', '0.1872', '0.194', '0.0019', '0.0049', '0.0699', '0.1815', '0.0201', 'San Francisco']
['Santa Clara University', '0.5122', '27.0', '42156.0', '0.4785', '0.0298', '0.1745', '0.144', '0.0013', '0.0024', '0.0661', '0.0298', '0.0736', 'Santa Clara']
['Scripps College', '0.357', '29.0', '45564.0', '0.5051', '0.0306', '0.0816', '0.1694', '0.0', '0.0031', '0.0724', '0.0408', '0.0969', 'Claremont']
['Simpson University', '0.555', '21.0', '23300.0', '0.624', '0.0293', '0.1367', '0.0586', '0.0371', '0.0049', '0.002', '0.0', '0.1074', 'Redding']
['University of Southern California', '0.1984', '29.0', '46298.0', '0.3812', '0.0442', '0.1355', '0.2306', '0.0013', '0.0012', '0.0475', '0.1209', '0.0378', 'Los Angeles']
['Colorado College', '0.2228', '27.0', '44222.0', '0.6963', '0.0212', '0.0884', '0.0435', '0.0044', '0.0', '0.0785', '0.0612', '0.0064', 'Colorado Springs']
['Colorado School of Mines', '0.3743', '27.0', '32415.0', '0.7529', '0.0117', '0.0803', '0.0467', '0.0019', '0.0002', '0.0422', '0.0434', '0.0207', 'Golden']
['University of Connecticut', '0.5321', '25.0', '30970.0', '0.6349', '0.0522', '0.0784', '0.0882', '0.0014', '0.0007', '0.0256', '0.0344', '0.0843', 'Storrs']
['Quinnipiac University', '0.6722', '22.0', '39330.0', '0.7831', '0.0442', '0.082', '0.022', '0.0026', '0.0006', '0.0171', '0.0196', '0.0287', 'Hamden']
['Trinity College', '0.3178', '25.0', '47510.0', '0.6498', '0.063', '0.0728', '0.0451', '0.0004', '0.0', '0.0331', '0.0826', '0.0531', 'Hartford']
['Wesleyan University', '0.2092', '29.0', '47244.0', '0.5294', '0.072', '0.0966', '0.0796', '0.0007', '0.001', '0.0582', '0.0828', '0.0796', 'Middletown']
['Yale University', '0.0705', '32.0', '44000.0', '0.4734', '0.0673', '0.1013', '0.1645', '0.0057', '0.0006', '0.0598', '0.1051', '0.0223', 'New Haven']
['University of Delaware', '0.6468', '24.0', '29932.0', '0.7529', '0.0531', '0.0694', '0.0426', '0.0007', '0.0011', '0.0264', '0.0416', '0.0121', 'Newark']
['American University', '0.4312', '26.0', '40649.0', '0.5671', '0.064', '0.1012', '0.0638', '0.0018', '0.0004', '0.0499', '0.0688', '0.0829', 'Washington']
['Catholic University of America', '0.6007', '22.0', '38526.0', '0.6311', '0.0549', '0.1052', '0.0313', '0.0016', '0.0011', '0.0313', '0.0481', '0.0953', 'Washington']
['George Washington University', '0.3308', '27.0', '47343.0', '0.6026', '0.0653', '0.0739', '0.0948', '0.002', '0.0007', '0.033', '0.0879', '0.0398', 'Washington']
['Georgetown University', '0.1697', '29.0', '44805.0', '0.5886', '0.0638', '0.0788', '0.0919', '0.0014', '0.0008', '0.0394', '0.1073', '0.0281', 'Washington']
['Howard University', '0.493', '21.0', '22683.0', '0.0134', '0.9183', '0.0036', '0.013', '0.0197', '0.0039', '0.0', '0.028', '0.0', 'Washington']
['University of Central Florida', '0.4894', '23.0', '22416.0', '0.5718', '0.1056', '0.2158', '0.0559', '0.0022', '0.0025', '0.029', '0.0095', '0.0077', 'Orlando']
['Flagler College-St Augustine', '0.4987', '21.0', '16180.0', '0.7584', '0.0395', '0.0814', '0.006', '0.0039', '0.0007', '0.0257', '0.0335', '0.0511', 'Saint Augustine']
['Florida Institute of Technology', '0.6045', '23.0', '36020.0', '0.4253', '0.0526', '0.0611', '0.0185', '0.0009', '0.0013', '0.0229', '0.3027', '0.1147', 'Melbourne']
['Florida International University', '0.4304', '24.0', '18895.0', '0.1007', '0.1221', '0.6705', '0.0269', '0.0008', '0.0014', '0.018', '0.0472', '0.0124', 'Miami']
['Florida Southern College', '0.4989', '22.0', '28580.0', '0.7243', '0.0593', '0.0925', '0.0164', '0.0017', '0.0013', '0.0399', '0.0542', '0.0105', 'Lakeland']
['Florida State University', '0.5681', '25.0', '21673.0', '0.667', '0.085', '0.1704', '0.0251', '0.0038', '0.0018', '0.0228', '0.0104', '0.0137', 'Tallahassee']
['University of Florida', '0.4655', '26.0', '28541.0', '0.5843', '0.074', '0.1902', '0.0754', '0.0026', '0.007', '0.0282', '0.0105', '0.0277', 'Gainesville']
['University of Miami', '0.4044', '28.0', '42852.0', '0.4302', '0.0728', '0.2171', '0.0538', '0.0015', '0.0012', '0.0268', '0.1344', '0.0623', 'Coral Gables']
['University of North Florida', '0.5343', '23.0', '20756.0', '0.6997', '0.0985', '0.0929', '0.0432', '0.0011', '0.0009', '0.0471', '0.0131', '0.0034', 'Jacksonville']
['Nova Southeastern University', '0.5746', '21.0', '25430.0', '0.3129', '0.2098', '0.3101', '0.0657', '0.0028', '0.0016', '0.0154', '0.0501', '0.0317', 'Fort Lauderdale']
['Rollins College', '0.5889', '24.0', '41460.0', '0.63', '0.0625', '0.1599', '0.0253', '0.0012', '0.0019', '0.0272', '0.0648', '0.0272', 'Winter Park']
['University of South Florida-Main Campus', '0.4499', '23.0', '17324.0', '0.5493', '0.1106', '0.1961', '0.0603', '0.0021', '0.0029', '0.0322', '0.0317', '0.0147', 'Tampa']
['Stetson University', '0.5925', '23.0', '38330.0', '0.6562', '0.0819', '0.1387', '0.0207', '0.003', '0.0007', '0.0421', '0.0443', '0.0125', 'DeLand']
['The University of Tampa', '0.5221', '21.0', '25772.0', '0.5923', '0.0576', '0.12', '0.0134', '0.0019', '0.0012', '0.0236', '0.1039', '0.086', 'Tampa']
['The University of West Florida', '0.4808', '21.0', '19238.0', '0.6741', '0.1264', '0.0889', '0.0297', '0.0073', '0.0038', '0.044', '0.0154', '0.0103', 'Pensacola']
['Berry College', '0.6032', '24.0', '29090.0', '0.845', '0.0396', '0.0575', '0.0108', '0.0019', '0.0009', '0.0264', '0.0066', '0.0113', 'Mount Berry']
['Covenant College', '0.5704', '23.0', '29100.0', '0.8833', '0.0329', '0.0226', '0.0216', '0.0056', '0.0009', '0.016', '0.0169', '0.0', 'Lookout Mountain']
['Emory University', '0.2633', '29.0', '44008.0', '0.4048', '0.0924', '0.0623', '0.2204', '0.0014', '0.0001', '0.0278', '0.1508', '0.04', 'Atlanta']
['Georgia Institute of Technology-Main Campus', '0.5493', '28.0', '29954.0', '0.553', '0.0628', '0.065', '0.175', '0.0013', '0.0009', '0.0323', '0.1048', '0.0049', 'Atlanta']
['Georgia College and State University', '0.6798', '22.0', '26690.0', '0.8518', '0.0488', '0.0488', '0.013', '0.0014', '0.0009', '0.024', '0.0087', '0.0027', 'Milledgeville']
['Georgia Southern University', '0.52', '21.0', '16137.0', '0.6328', '0.2599', '0.04', '0.0136', '0.0047', '0.0015', '0.0194', '0.0125', '0.0157', 'Statesboro']
['University of Georgia', '0.5608', '26.0', '28472.0', '0.7297', '0.074', '0.052', '0.0895', '0.0009', '0.0011', '0.0299', '0.0122', '0.0107', 'Athens']
['Kennesaw State University', '0.5654', '21.0', '15898.0', '0.629', '0.1769', '0.0722', '0.033', '0.0022', '0.0015', '0.0379', '0.0189', '0.0284', 'Kennesaw']
['Mercer University', '0.69', '23.0', '33120.0', '0.4747', '0.3322', '0.0372', '0.0511', '0.0044', '0.0014', '0.0193', '0.0344', '0.0453', 'Macon']
['Oglethorpe University', '0.5576', '22.0', '31280.0', '0.349', '0.1843', '0.101', '0.0392', '0.0029', '0.0', '0.0216', '0.0461', '0.2559', 'Atlanta']
['Savannah College of Art and Design', '0.6547', '21.0', '33450.0', '0.5605', '0.1086', '0.0805', '0.044', '0.0056', '0.0023', '0.0023', '0.1168', '0.0795', 'Savannah']
['Northwest Nazarene University', '0.617', '21.0', '26550.0', '0.7354', '0.0144', '0.0751', '0.0144', '0.0048', '0.0032', '0.016', '0.0192', '0.1175', 'Nampa']
['Bradley University', '0.6694', '23.0', '29664.0', '0.79', '0.0616', '0.0587', '0.0344', '0.0025', '0.001', '0.0379', '0.0085', '0.0054', 'Peoria']
['University of Chicago', '0.0881', '32.0', '47514.0', '0.4546', '0.0453', '0.0869', '0.1813', '0.0018', '0.0005', '0.0374', '0.0937', '0.0985', 'Chicago']
['DePaul University', '0.5987', '23.0', '33990.0', '0.5561', '0.0837', '0.1717', '0.073', '0.001', '0.0021', '0.0371', '0.0265', '0.0488', 'Chicago']
['University of Illinois at Urbana-Champaign', '0.6239', '26.0', '29132.0', '0.5315', '0.0554', '0.0825', '0.1518', '0.0006', '0.0015', '0.0253', '0.1462', '0.0052', 'Champaign']
['Illinois Wesleyan University', '0.5838', '25.0', '39316.0', '0.738', '0.046', '0.063', '0.046', '0.003', '0.0005', '0.014', '0.049', '0.0405', 'Bloomington']
['Illinois Institute of Technology', '0.5697', '25.0', '40117.0', '0.373', '0.0683', '0.1471', '0.1082', '0.0042', '0.0042', '0.0046', '0.2452', '0.0452', 'Chicago']
['Illinois State University', '0.6892', '22.0', '20450.0', '0.7969', '0.0714', '0.0771', '0.02', '0.0018', '0.001', '0.0223', '0.0046', '0.005', 'Normal']
['Lake Forest College', '0.5727', '23.0', '39842.0', '0.5764', '0.0615', '0.1452', '0.0488', '0.0032', '0.0013', '0.0342', '0.1015', '0.0279', 'Lake Forest']
['Lewis University', '0.5587', '21.0', '26780.0', '0.6471', '0.076', '0.1729', '0.0341', '0.0011', '0.002', '0.0209', '0.0082', '0.0376', 'Romeoville']
['Millikin University', '0.5512', '21.0', '28644.0', '0.7587', '0.1239', '0.0561', '0.0075', '0.0014', '0.0009', '0.0358', '0.0123', '0.0033', 'Decatur']
['North Central College', '0.6365', '22.0', '32613.0', '0.7752', '0.0348', '0.0826', '0.0207', '0.0026', '0.0007', '0.0304', '0.013', '0.04', 'Naperville']
['Northwestern University', '0.1532', '31.0', '45527.0', '0.5432', '0.0567', '0.0966', '0.1704', '0.0026', '0.0', '0.0473', '0.0688', '0.0145', 'Evanston']
['University of St Francis', '0.5141', '21.0', '27970.0', '0.7223', '0.074', '0.1343', '0.0262', '0.004', '0.004', '0.0205', '0.0125', '0.0023', 'Joliet']
['VanderCook College of Music', '0.374', '24.0', '24890.0', '0.6635', '0.0577', '0.2115', '0.0096', '0.0', '0.0', '0.0288', '0.0288', '0.0', 'Chicago']
['Wheaton College', '0.6871', '27.0', '30880.0', '0.7822', '0.0215', '0.0493', '0.082', '0.0008', '0.0', '0.0451', '0.0186', '0.0004', 'Wheaton']
['Anderson University', '0.5545', '21.0', '26280.0', '0.811', '0.0575', '0.0269', '0.007', '0.0032', '0.0027', '0.0043', '0.0328', '0.0548', 'Anderson']
['Butler University', '0.661', '25.0', '34368.0', '0.8269', '0.0353', '0.032', '0.0283', '0.002', '0.0', '0.014', '0.0225', '0.039', 'Indianapolis']
['DePauw University', '0.6121', '25.0', '40640.0', '0.6822', '0.0643', '0.0335', '0.0308', '0.0035', '0.0', '0.0585', '0.1004', '0.0268', 'Greencastle']
['Earlham College', '0.637', '26.0', '41450.0', '0.5354', '0.1348', '0.0581', '0.0374', '0.0089', '0.0', '0.003', '0.1969', '0.0256', 'Richmond']
['Goshen College', '0.5506', '21.0', '28500.0', '0.7172', '0.0398', '0.1195', '0.0064', '0.0', '0.0', '0.0296', '0.0823', '0.0051', 'Goshen']
['Hanover College', '0.6673', '23.0', '31760.0', '0.8223', '0.0449', '0.0242', '0.0104', '0.0043', '0.0', '0.0242', '0.0457', '0.0242', 'Hanover']
['University of Notre Dame', '0.223', '32.0', '44605.0', '0.7126', '0.0357', '0.1024', '0.0601', '0.0039', '0.0001', '0.039', '0.0408', '0.0054', 'Notre Dame']
['Rose-Hulman Institute of Technology', '0.5622', '27.0', '42654.0', '0.7755', '0.0245', '0.0286', '0.037', '0.0018', '0.0018', '0.0346', '0.0924', '0.0037', 'Terre Haute']
['Central College', '0.658', '21.0', '30700.0', '0.8956', '0.0192', '0.0269', '0.0077', '0.0023', '0.0015', '0.013', '0.0038', '0.0299', 'Pella']
['Coe College', '0.6171', '23.0', '35730.0', '0.7882', '0.0406', '0.0546', '0.0236', '0.0022', '0.0', '0.0339', '0.0192', '0.0376', 'Cedar Rapids']
['Cornell College', '0.6411', '23.0', '36430.0', '0.6488', '0.0535', '0.1283', '0.0312', '0.0071', '0.0027', '0.0294', '0.057', '0.0419', 'Mount Vernon']
['Drake University', '0.6595', '25.0', '30889.0', '0.7937', '0.0323', '0.0326', '0.0447', '0.0018', '0.0006', '0.013', '0.0695', '0.0118', 'Des Moines']
['Grinnell College', '0.3506', '28.0', '43656.0', '0.5798', '0.059', '0.0837', '0.0753', '0.0018', '0.0', '0.0427', '0.1264', '0.0313', 'Grinnell']
['Loras College', '0.6903', '21.0', '28852.0', '0.8291', '0.0224', '0.0598', '0.0079', '0.002', '0.0007', '0.0151', '0.025', '0.0381', 'Dubuque']
['Benedictine College', '0.6057', '22.0', '23900.0', '0.8023', '0.0343', '0.06', '0.0109', '0.004', '0.0029', '0.0309', '0.0297', '0.0251', 'Atchison']
['Asbury University', '0.6573', '21.0', '26076.0', '0.8348', '0.033', '0.0151', '0.0057', '0.0029', '0.0014', '0.0481', '0.0158', '0.0431', 'Wilmore']
['Berea College', '0.3401', '22.0', '23170.0', '0.6446', '0.1512', '0.0422', '0.0151', '0.0025', '0.0019', '0.051', '0.0756', '0.0158', 'Berea']
['Centre College', '0.6857', '26.0', '36020.0', '0.8287', '0.0481', '0.0248', '0.0248', '0.0', '0.0', '0.0292', '0.0415', '0.0029', 'Danville']
['University of Kentucky', '0.6861', '22.0', '21192.0', '0.778', '0.0779', '0.0326', '0.0247', '0.0017', '0.0007', '0.0285', '0.0262', '0.0298', 'Lexington']
['Centenary College of Louisiana', '0.6597', '22.0', '30740.0', '0.6978', '0.152', '0.0553', '0.0276', '0.0069', '0.0017', '0.0328', '0.0242', '0.0017', 'Shreveport']
['Louisiana Tech University', '0.6744', '21.0', '18441.0', '0.6823', '0.1506', '0.0139', '0.0099', '0.0048', '0.0011', '0.0145', '0.0444', '0.0785', 'Ruston']
['University of New Orleans', '0.5036', '21.0', '19068.0', '0.5626', '0.1548', '0.0988', '0.0779', '0.0045', '0.0006', '0.0274', '0.0317', '0.0417', 'New Orleans']
['University of Louisiana at Lafayette', '0.593', '21.0', '15742.0', '0.6842', '0.213', '0.0316', '0.0193', '0.0043', '0.0008', '0.0158', '0.022', '0.0091', 'Lafayette']
['Tulane University of Louisiana', '0.2643', '29.0', '46930.0', '0.718', '0.0901', '0.0585', '0.0364', '0.0039', '0.0008', '0.0293', '0.0303', '0.0327', 'New Orleans']
['Bowdoin College', '0.1495', '30.0', '45446.0', '0.6417', '0.047', '0.1247', '0.0699', '0.0011', '0.0006', '0.062', '0.047', '0.0061', 'Brunswick']
['Colby College', '0.2604', '28.0', '45760.0', '0.5967', '0.033', '0.0626', '0.0544', '0.0005', '0.0', '0.0478', '0.0841', '0.1209', 'Waterville']
['Johns Hopkins University', '0.1813', '30.0', '45470.0', '0.4872', '0.0556', '0.1015', '0.1861', '0.0012', '0.0007', '0.0406', '0.1043', '0.0228', 'Baltimore']
['Loyola University Maryland', '0.58', '25.0', '43250.0', '0.7941', '0.0506', '0.0921', '0.0302', '0.002', '0.0005', '0.0214', '0.0038', '0.0053', 'Baltimore']
['University of Maryland-Baltimore County', '0.6315', '24.0', '21642.0', '0.4521', '0.1594', '0.0568', '0.1983', '0.0015', '0.0015', '0.036', '0.0423', '0.0522', 'Baltimore']
['Salisbury University', '0.5494', '22.0', '16474.0', '0.7401', '0.1125', '0.0444', '0.0246', '0.0026', '0.0008', '0.0375', '0.0108', '0.0268', 'Salisbury']
['Towson University', '0.6034', '21.0', '20020.0', '0.6521', '0.1526', '0.0521', '0.0478', '0.0018', '0.0009', '0.0349', '0.0203', '0.0375', 'Towson']
['Washington College', '0.6655', '24.0', '41120.0', '0.7872', '0.033', '0.0365', '0.0126', '0.0014', '0.0', '0.0232', '0.0639', '0.0421', 'Chestertown']
['Amherst College', '0.1428', '30.0', '46574.0', '0.4174', '0.1165', '0.1283', '0.1255', '0.0011', '0.0', '0.056', '0.0958', '0.0594', 'Amherst']
['Babson College', '0.2821', '26.0', '43520.0', '0.3898', '0.0423', '0.0997', '0.1168', '0.0019', '0.0', '0.0223', '0.2635', '0.0636', 'Wellesley']
['Bentley University', '0.4379', '26.0', '41110.0', '0.6146', '0.0295', '0.0686', '0.0803', '0.001', '0.0', '0.0177', '0.1453', '0.0431', 'Waltham']
['Boston College', '0.3222', '30.0', '45622.0', '0.5797', '0.0432', '0.1055', '0.0937', '0.0007', '0.0003', '0.028', '0.052', '0.0968', 'Chestnut Hill']
['Boston University', '0.4561', '26.0', '44880.0', '0.4733', '0.0323', '0.0928', '0.1326', '0.0007', '0.001', '0.0376', '0.1586', '0.071', 'Boston']
['Brandeis University', '0.3704', '28.0', '45856.0', '0.501', '0.0516', '0.0655', '0.1243', '0.0006', '0.0', '0.028', '0.1482', '0.0808', 'Waltham']
['Emerson College', '0.4798', '26.0', '35730.0', '0.6465', '0.0296', '0.1022', '0.0387', '0.0005', '0.0008', '0.0457', '0.0465', '0.0895', 'Boston']

In [59]:
import csv
f = open('crime_data.csv') #open "crime_data" file
csv_f = csv.reader(f) #can read this data in python (read this page)

for row in csv_f: #for loop, list/print out every single column in this file.
    print(row)
#ynl

['MSA', 'ViolentCrime', 'Murder', 'Rape', 'Robbery', 'AggravatedAssault', 'PropertyCrime', 'Burglary', 'Theft', 'MotorVehicleTheft', 'State', 'City']
['Altoona, PA M.S.A.', '216.5', '0.8', '28.7', '25.5', '161.6', '1430.2', '218.9', '1163.6', '47.8', 'PA', 'Altoona']
['Ames, IA M.S.A.', '158.5', '1.0', '47.2', '19.9', '90.3', '1848.3', '311.7', '1462.0', '74.5', 'IA', 'Ames']
['Ann Arbor, MI M.S.A.', '319.5', '1.9', '57.0', '51.4', '209.2', '1791.9', '290.4', '1417.4', '84.2', 'MI', 'Ann Arbor']
['Appleton, WI M.S.A.', '138.8', '0.4', '24.1', '8.6', '105.7', '1394.9', '206.6', '1154.7', '33.5', 'WI', 'Appleton']
['Bangor, ME M.S.A.', '67.3', '2.0', '9.1', '17.6', '38.5', '1984.5', '337.0', '1604.4', '43.1', 'ME', 'Bangor']
['Bay City, MI M.S.A.', '283.4', '0.0', '80.3', '36.8', '166.3', '2100.4', '497.0', '1520.2', '83.1', 'MI', 'Bay City']
['Bismarck, ND M.S.A.', '227.1', '3.1', '37.1', '13.1', '173.8', '1667.6', '188.5', '1320.1', '159.1', 'ND', 'Bismarck']
['Bloomington, IL M.S.A.', '252.0', '0.0', '61.8', '32.0', '158.2', '1668.6', '322.2', '1278.3', '68.1', 'IL', 'Bloomington']
['Bloomsburg-Berwick, PA M.S.A', '152.7', '1.2', '22.2', '7.0', '122.4', '1325.8', '240.2', '1057.6', '28.0', 'PA', 'Bloomsburg']
['Boise City, ID M.S.A.', '233.9', '1.8', '49.3', '13.7', '169.1', '1725.3', '315.3', '1286.4', '123.6', 'ID', 'Boise']
['Bowling Green, KY M.S.A.', '173.4', '0.6', '44.2', '52.0', '76.5', '2405.6', '477.2', '1784.9', '143.5', 'KY', 'Bowling Green']
['Bridgeport-Stamford-Norwalk, CT M.S.A.', '201.5', '2.5', '21.8', '76.9', '100.3', '1473.2', '236.6', '1090.9', '145.7', 'CT', 'Bridgeport']
['Burlington-South Burlington, VT M.S.A.', '128.5', '0.9', '23.0', '21.7', '82.9', '1955.4', '375.4', '1564.3', '15.7', 'VT', 'Burlington']
['California-Lexington Park, MD M.S.A.', '266.1', '0.9', '18.0', '45.8', '201.4', '2055.1', '490.0', '1503.1', '62.0', 'MD', 'California']
['Cape Coral-Fort Myers, FL M.S.A.', '356.1', '4.4', '29.5', '80.9', '241.3', '1801.2', '407.0', '1270.8', '123.4', 'FL', 'Cape Coral']
['Carson City, NV M.S.A.', '314.7', '1.8', '3.7', '36.6', '272.6', '1829.7', '336.7', '1341.2', '151.9', 'NV', 'Carson City']
['Cedar Rapids, IA M.S.A.', '189.5', '3.0', '18.8', '43.7', '123.9', '2350.4', '532.3', '1681.7', '136.4', 'IA', 'Cedar Rapids']
['Chambersburg-Waynesboro, PA M.S.A.', '159.5', '2.0', '37.8', '43.0', '76.8', '1619.8', '307.3', '1233.1', '79.4', 'PA', 'Chambersburg']
['Charlottesville, VA M.S.A.', '164.6', '1.3', '35.5', '31.5', '96.3', '1514.5', '252.2', '1199.2', '63.0', 'VA', 'Charlottesville']
['Elgin, IL M.D.', '189.4', '1.6', '28.5', '37.2', '122.0', '1342.2', '188.1', '1112.0', '42.1', 'IL', 'Elgin']
['Lake County-Kenosha County, IL-WI M.D.', '158.9', '2.2', '24.0', '46.9', '85.9', '1527.6', '254.9', '1212.2', '60.5', 'IL', 'Kenosha']
["Coeur d'Alene, ID M.S.A.", '259.6', '1.3', '45.4', '22.0', '190.9', '2176.1', '465.8', '1592.9', '117.4', 'ID', "Coeur d'Alene"]
['Daphne-Fairhope-Foley, AL M.S.A.', '195.3', '1.5', '21.5', '36.7', '135.6', '2064.5', '357.4', '1627.3', '79.8', 'AL', 'Daphne']
['Warren-Troy-Farmington Hills, MI M.D.', '220.6', '1.6', '37.4', '33.9', '147.7', '1371.0', '235.8', '1022.4', '112.8', 'MI', 'Warren']
['East Stroudsburg, PA M.S.A.', '191.1', '1.2', '36.9', '62.3', '90.7', '2264.1', '511.0', '1696.3', '56.8', 'PA', 'East Stroudsburg']
['Eau Claire, WI M.S.A.', '129.1', '0.0', '21.1', '12.1', '95.9', '1669.1', '278.7', '1305.4', '85.1', 'WI', 'Eau Claire']
['Elizabethtown-Fort Knox, KY M.S.A.', '104.7', '3.3', '22.4', '21.1', '58.0', '1232.2', '272.0', '904.2', '56.0', 'KY', 'Elizabethtown']
['Elmira, NY M.S.A.', '182.1', '2.3', '30.9', '48.1', '100.8', '1996.4', '315.0', '1635.6', '45.8', 'NY', 'Elmira']
['El Paso, TX M.S.A.', '354.3', '2.7', '43.7', '52.6', '255.3', '1825.1', '220.8', '1491.7', '112.6', 'TX', 'El Paso']
['Erie, PA M.S.A.', '234.4', '4.0', '33.8', '61.6', '135.0', '2052.0', '444.6', '1540.8', '66.6', 'PA', 'Erie']
['Fargo, ND-MN M.S.A.', '249.3', '2.6', '49.8', '27.9', '169.1', '2403.4', '451.8', '1766.2', '185.4', 'ND', 'Fargo']
['Fond du Lac, WI M.S.A.', '214.3', '1.0', '51.1', '12.8', '149.4', '1380.2', '179.9', '1146.3', '54.1', 'WI', 'Fond du Lac']
['Fort Collins, CO M.S.A.', '199.1', '2.1', '27.4', '21.1', '148.4', '2229.0', '281.4', '1819.4', '128.2', 'CO', 'Fort Collins']
['Fort Wayne, IN M.S.A.', '288.0', '6.5', '30.5', '122.2', '128.8', '2328.3', '434.7', '1782.3', '111.3', 'IN', 'Fort Wayne']
['Gainesville, GA M.S.A.', '188.8', '2.6', '22.2', '35.6', '128.4', '1845.1', '373.5', '1328.8', '142.9', 'GA', 'Gainesville']
['Gettysburg, PA M.S.A.', '135.6', '0.0', '34.4', '13.8', '87.5', '983.9', '243.8', '705.7', '34.4', 'PA', 'Gettysburg']
['Grand Forks, ND-MN M.S.A.', '243.8', '2.9', '60.5', '26.3', '154.1', '2108.0', '304.2', '1655.6', '148.2', 'ND', 'Grand Forks']
['Grand Island, NE M.S.A.', '215.2', '0.0', '59.6', '15.2', '140.3', '2185.8', '364.9', '1699.3', '121.6', 'NE', 'Grand Island']
['Grand Rapids-Wyoming, MI M.S.A.', '329.0', '1.7', '75.1', '59.8', '192.3', '1618.2', '301.4', '1236.4', '80.4', 'MI', 'Grand Rapids']
['Greeley, CO M.S.A.', '270.6', '1.8', '47.0', '25.3', '196.5', '1695.9', '300.4', '1260.7', '134.8', 'CO', 'Greeley']
['Green Bay, WI M.S.A.', '196.6', '1.3', '25.0', '24.7', '145.7', '1453.9', '217.8', '1177.3', '58.8', 'WI', 'Green Bay']
['Hagerstown-Martinsburg, MD-WV M.S.A.', '260.7', '4.2', '20.7', '68.1', '167.7', '2123.7', '494.9', '1515.0', '113.7', 'MD', 'Hagerstown']
['Harrisonburg, VA M.S.A.', '145.8', '0.8', '36.5', '11.4', '97.2', '1555.7', '302.3', '1200.9', '52.4', 'VA', 'Harrisonburg']
['Hilton Head Island-Bluffton-Beaufort, SC M.S.A.', '349.4', '13.5', '44.3', '73.3', '218.3', '2403.8', '497.8', '1770.5', '135.4', 'SC', 'Bluffton']
['Hinesville, GA M.S.A.', '304.4', '1.2', '10.7', '60.9', '231.6', '2270.3', '490.6', '1656.8', '122.9', 'GA', '']
['Homosassa Springs, FL M.S.A.', '308.7', '1.4', '35.8', '28.6', '242.8', '1438.8', '301.5', '1055.6', '81.6', 'FL', 'Spring']
['Idaho Falls, ID M.S.A.', '183.9', '1.4', '31.5', '6.4', '144.6', '1822.8', '342.1', '1365.5', '115.2', 'ID', 'Idaho Falls']
['Iowa City, IA M.S.A.', '263.4', '0.6', '53.8', '28.1', '181.0', '1981.6', '359.5', '1549.2', '72.9', 'IA', 'Iowa City']
['Janesville-Beloit, WI M.S.A.', '238.7', '3.7', '29.1', '47.1', '158.7', '2347.4', '392.4', '1854.0', '101.0', 'WI', 'Janesville']
['Jefferson City, MO M.S.A.', '258.7', '1.3', '31.8', '38.4', '187.2', '1919.1', '346.0', '1469.9', '103.2', 'MO', 'Jefferson City']
['Johnson City, TN M.S.A.', '302.0', '5.5', '19.8', '30.3', '246.5', '2428.9', '475.1', '1851.2', '102.7', 'TN', 'Johnson City']
['Johnstown, PA M.S.A.', '199.6', '4.4', '19.1', '32.3', '143.8', '1633.9', '292.0', '1303.0', '38.9', 'PA', 'Johnstown']
['Kennewick-Richland, WA M.S.A.', '182.3', '2.9', '36.0', '27.5', '116.0', '2115.7', '392.5', '1602.2', '121.0', 'WA', 'Kennewick']
['Kingsport-Bristol-Bristol, TN-VA M.S.A.', '317.7', '3.6', '36.4', '31.2', '246.5', '2401.1', '463.1', '1772.8', '165.2', 'TN', 'Bristol']
['Kingston, NY M.S.A.', '169.3', '0.0', '53.4', '22.8', '93.0', '1496.6', '227.7', '1229.9', '39.0', 'NY', 'Kingston']
['La Crosse-Onalaska, WI-MN M.S.A.', '116.5', '1.5', '21.1', '13.8', '80.1', '2179.9', '316.6', '1808.0', '55.3', 'WI', 'La Crosse']
['Lafayette-West Lafayette, IN M.S.A.', '292.0', '1.9', '36.0', '59.3', '194.8', '2509.3', '503.6', '1847.3', '158.4', 'IN', 'Lafayette']
['Lancaster, PA M.S.A.', '180.4', '3.0', '42.5', '51.1', '83.9', '1422.0', '212.1', '1164.3', '45.5', 'PA', 'Lancaster']
['Lebanon, PA M.S.A.', '185.4', '2.9', '18.3', '31.4', '132.9', '1549.1', '256.2', '1208.2', '84.7', 'PA', 'Lebanon']
['Lewiston-Auburn, ME M.S.A.', '138.0', '0.0', '39.2', '28.9', '69.9', '1774.1', '353.3', '1349.9', '70.9', 'ME', 'Lewiston']
['Logan, UT-ID M.S.A.', '61.6', '0.8', '33.1', '2.3', '25.5', '1201.2', '208.1', '950.3', '42.8', 'UT', 'Logan']
['Lynchburg, VA M.S.A.', '180.4', '3.5', '29.0', '27.9', '120.0', '1455.2', '230.3', '1155.7', '69.3', 'VA', 'Lynchburg']
['Madison, WI M.S.A.', '211.9', '2.7', '29.7', '46.8', '132.7', '1956.7', '310.1', '1580.9', '65.7', 'WI', 'Madison']
['Manchester-Nashua, NH M.S.A.', '281.4', '3.2', '46.7', '70.3', '161.1', '1923.7', '287.0', '1547.0', '89.8', 'NH', 'Manchester']
['Manhattan, KS M.S.A.', '229.9', '2.0', '36.3', '25.2', '166.3', '1687.7', '378.1', '1216.9', '92.8', 'KS', 'Manhattan']
['Mankato-North Mankato, MN M.S.A.', '152.8', '0.0', '37.4', '22.3', '93.1', '2324.8', '401.8', '1821.8', '101.2', 'MN', 'Mankato']
['Midland, MI M.S.A.', '143.9', '2.4', '66.0', '3.6', '71.9', '1108.0', '206.2', '881.3', '20.4', 'MI', 'Midland']
['Midland, TX M.S.A.', '322.3', '5.4', '28.2', '47.3', '241.4', '2590.8', '524.1', '1891.7', '174.9', 'TX', 'Midland']
['Minneapolis-St. Paul-Bloomington, MN-WI M.S.A.', '285.2', '2.7', '40.8', '97.1', '144.6', '2367.5', '353.6', '1842.4', '171.4', 'MN', 'Minneapolis']
['Monroe, MI M.S.A.', '236.3', '2.0', '69.6', '30.1', '134.6', '1692.6', '447.9', '1154.3', '90.4', 'MI', 'Monroe']
['Morgantown, WV M.S.A.', '267.6', '2.2', '46.2', '38.2', '181.0', '1670.5', '436.4', '1153.3', '80.8', 'WV', 'Morgantown']
['Naples-Immokalee-Marco Island, FL M.S.A.', '286.7', '0.6', '29.7', '46.7', '209.8', '1347.7', '264.9', '1007.3', '75.5', 'FL', 'Naples']
['Norwich-New London, CT M.S.A.', '323.7', '4.1', '39.2', '69.4', '211.0', '2040.0', '297.6', '1631.7', '110.7', 'CT', 'Norwich']
['Ocala, FL M.S.A.', '363.1', '2.9', '33.2', '57.5', '269.5', '2096.6', '501.9', '1496.4', '98.3', 'FL', 'Ocala']
['Oshkosh-Neenah, WI M.S.A.', '177.6', '2.4', '17.1', '24.1', '134.1', '1683.8', '282.9', '1345.0', '55.9', 'WI', 'Oshkosh']
['Owensboro, KY M.S.A.', '136.1', '0.0', '37.7', '44.5', '53.9', '2252.4', '387.8', '1747.3', '117.3', 'KY', 'Owensboro']
['Peoria, IL M.S.A.', '358.2', '4.5', '44.8', '93.6', '215.3', '2222.7', '497.1', '1653.7', '72.0', 'IL', 'Peoria']
['Camden, NJ M.D.2', '272.0', '3.6', '18.2', '93.9', '156.3', '2022.5', '426.6', '1503.3', '92.6', 'NJ', 'Camden']
['Montgomery County-Bucks County-Chester County, PA M.D.', '128.2', '1.5', '13.1', '37.0', '76.5', '1447.2', '174.9', '1219.6', '52.7', 'PA', 'Montgomery']
['Pittsburgh, PA M.S.A.', '266.3', '4.7', '17.6', '76.4', '167.6', '1782.9', '321.6', '1389.0', '72.3', 'PA', 'Pittsburgh']
['Portland-South Portland, ME M.S.A.', '134.6', '0.8', '24.4', '35.6', '73.8', '1833.7', '325.8', '1448.0', '60.0', 'ME', 'Portland']
['Port St. Lucie, FL M.S.A.', '286.2', '3.1', '28.6', '54.2', '200.3', '1840.8', '338.9', '1413.5', '88.3', 'FL', 'Port St Lucie']
['Prescott, AZ M.S.A.', '294.0', '4.1', '25.7', '12.2', '252.0', '2036.0', '359.5', '1562.7', '113.8', 'AZ', 'Prescott']
['Providence-Warwick, RI-MA M.S.A.', '333.7', '2.2', '39.1', '65.3', '227.2', '1876.8', '385.3', '1364.1', '127.4', 'RI', 'Providence']
['Provo-Orem, UT M.S.A.', '71.7', '0.3', '25.2', '7.9', '38.3', '1551.5', '188.1', '1275.4', '88.0', 'UT', 'Provo']
['Punta Gorda, FL M.S.A.', '202.2', '0.6', '18.1', '17.5', '166.1', '1509.5', '242.4', '1202.9', '64.1', 'FL', '']
['Racine, WI M.S.A.', '231.8', '2.1', '18.5', '90.3', '121.0', '2048.0', '512.4', '1466.4', '69.2', 'WI', 'Racine']
['Reading, PA M.S.A.', '309.2', '3.6', '22.7', '85.5', '197.3', '1681.6', '349.5', '1231.9', '100.2', 'PA', 'Reading']
['Richmond, VA M.S.A.', '236.5', '7.5', '25.2', '77.6', '126.3', '2351.7', '387.2', '1823.2', '141.3', 'VA', 'Richmond']
['Roanoke, VA M.S.A.', '213.9', '6.4', '33.2', '28.4', '146.0', '2128.6', '268.1', '1760.2', '100.4', 'VA', 'Roanoke']
['Rochester, MN M.S.A.', '127.6', '0.5', '29.0', '25.7', '72.4', '1514.4', '307.9', '1142.0', '64.5', 'MN', 'Rochester']
['Rochester, NY M.S.A.', '280.7', '3.8', '44.4', '82.1', '150.4', '2107.6', '388.3', '1609.4', '109.9', 'NY', 'Rochester']
['Sebastian-Vero Beach, FL M.S.A.', '265.6', '1.4', '24.5', '27.2', '212.6', '2411.0', '480.3', '1828.8', '101.9', 'FL', 'San Sebastian']
['Sheboygan, WI M.S.A.', '174.5', '2.6', '26.0', '16.5', '129.4', '1569.7', '159.7', '1363.9', '46.0', 'WI', '']
['Sioux Falls, SD M.S.A.', '363.7', '1.2', '57.9', '35.3', '269.3', '2503.3', '492.2', '1826.7', '184.4', 'SD', 'Sioux Falls']
['State College, PA M.S.A.', '102.6', '1.3', '39.4', '8.1', '53.8', '1177.4', '175.2', '980.9', '21.3', 'PA', 'State College']
['Staunton-Waynesboro, VA M.S.A.', '139.4', '3.3', '28.4', '24.2', '83.5', '1483.3', '197.0', '1223.7', '62.6', 'VA', 'Staunton']
['St. George, UT M.S.A.', '133.3', '0.0', '37.8', '10.9', '84.6', '1676.2', '372.4', '1188.4', '115.4', 'UT', 'St. George']
['Syracuse, NY M.S.A.', '284.2', '4.1', '48.0', '73.1', '159.0', '2059.1', '383.4', '1597.7', '77.9', 'NY', 'Syracuse']
['The Villages, FL M.S.A.', '232.1', '0.8', '14.9', '16.6', '199.8', '940.9', '257.8', '632.5', '50.6', 'FL', 'The Villages']
['Utica-Rome, NY M.S.A.', '233.6', '2.7', '56.2', '38.9', '135.8', '1983.3', '355.5', '1558.4', '69.4', 'NY', 'Utica']
['Washington-Arlington-Alexandria, DC-VA-MD-WV M.S.A.', '324.1', '5.3', '27.2', '123.2', '168.3', '1929.2', '215.5', '1552.2', '161.5', 'DC', 'Washington']
['Silver Spring-Frederick-Rockville, MD M.D.', '204.2', '2.8', '23.9', '58.1', '119.4', '1559.0', '197.6', '1293.0', '68.4', 'MD', 'Silver Spring']
['Washington-Arlington-Alexandria, DC-VA-MD-WV M.D.', '356.0', '6.0', '28.1', '140.5', '181.4', '2027.9', '220.3', '1621.3', '186.3', 'DC', 'Washington']
['Watertown-Fort Drum, NY M.S.A.', '189.1', '2.5', '69.4', '15.9', '101.2', '1961.3', '332.2', '1586.4', '42.7', 'NY', 'Watertown']
['Wausau, WI M.S.A.', '110.9', '1.5', '18.4', '19.1', '72.0', '1208.5', '187.3', '985.1', '36.0', 'WI', 'Wausau']
['Wenatchee, WA M.S.A.', '100.3', '0.9', '17.3', '10.4', '71.8', '2110.6', '464.5', '1505.1', '141.0', 'WA', 'Wenatchee']
['Wheeling, WV-OH M.S.A.', '333.9', '3.5', '33.2', '39.5', '257.7', '1499.7', '334.6', '1092.4', '72.7', 'WV', 'Wheeling']
['Williamsport, PA M.S.A.', '209.3', '6.0', '48.0', '47.2', '108.1', '1790.6', '293.4', '1454.3', '42.9', 'PA', 'Williamsport']
['Winchester, VA-WV M.S.A.', '173.6', '1.5', '56.6', '28.3', '87.2', '2020.9', '321.0', '1603.7', '96.1', 'VA', 'Winchester']
['York-Hanover, PA M.S.A.', '217.5', '4.3', '23.3', '64.3', '125.6', '1551.4', '232.6', '1255.2', '63.6', 'PA', 'York']
['Aguadilla-Isabela, Puerto Rico M.S.A.', '108.7', '4.8', '3.5', '40.5', '59.9', '710.2', '284.5', '403.3', '22.5', 'Aguadilla-Isabela, Puerto Rico M.S.A.', 'Aguadilla']
['Arecibo, Puerto Rico M.S.A.', '99.3', '6.9', '2.7', '53.1', '36.6', '1031.9', '287.3', '670.8', '73.8', 'Arecibo, Puerto Rico M.S.A.', 'Arecibo']
['Guayama, Puerto Rico M.S.A.', '251.6', '11.4', '6.3', '74.6', '159.3', '823.2', '265.5', '531.1', '26.6', 'Guayama, Puerto Rico M.S.A.', 'Guayama']
['Mayaguez, Puerto Rico M.S.A.', '237.5', '11.5', '5.2', '82.3', '138.6', '1320.0', '377.1', '861.6', '81.3', 'Mayaguez, Puerto Rico M.S.A.', 'Mayaguez']
['Ponce, Puerto Rico M.S.A.', '231.4', '18.0', '5.0', '66.2', '142.2', '885.0', '214.4', '632.4', '38.1', 'Ponce, Puerto Rico M.S.A.', 'Ponce']
['San German, Puerto Rico M.S.A.', '92.1', '5.4', '4.6', '16.1', '66.0', '420.0', '168.9', '226.5', '24.6', 'San German, Puerto Rico M.S.A.', 'San German']
['San Juan-Carolina-Caguas, Puerto Rico M.S.A.', '262.0', '20.6', '4.9', '157.8', '78.7', '1281.2', '281.8', '835.0', '164.3', 'San Juan-Carolina-Caguas, Puerto Rico M.S.A.', 'San Juan']

In [3]:
import csv
f = open('college_data.csv')
csv_f_1 = csv.reader(f)
f = open('crime_data.csv')
csv_f_2 = csv.reader(f)

c_1 = [] #to define a variable for further use: to run for loop later
c_2 = []
for city_1 in csv_f_1: #in csv_f_1= in college data
    c_1.append(city_1[-1]) # only took last row in the data csv_f_1(which is college_data), which is "city".
for city_2 in csv_f_2:
    c_2.append(city_2[-1]) #only took last row in the data csv_f_2(which is crime_data), which is "city".

index_1 = [] #creat an empty list
index_2 = [] 
for i in range(len(c_1)): #for loop
    for j in range(len(c_2)): ##for loop 
        if c_1[i] == c_2[j]:      #condition: if c_1(city in college data) equals c_2(city in crime data)
                                  #for those cities which exist in both data, we collected them out and put it in an empty file for further use. 
            index_1.append(i)
            index_2.append(j)
print(index_1)
#print(index_2)  

#ynl,yrs

[0, 40, 40, 41, 41, 42, 42, 43, 43, 44, 44, 51, 72, 76, 90, 96, 109, 143, 146, 153, 186, 195, 195, 196, 196, 197, 200, 200, 207, 208, 217, 250, 251, 257, 259, 268, 272, 277, 278, 279, 289, 313, 321, 324, 330, 336, 346, 346]

In [61]:
vx = [] #created new empty list
simp = [] #created empty list,simp=simplified list

for i in range(len(c_1)): #for loop
    for j in range(len(c_2)):# for loop
        if c_1[i] == c_2[j]:#if data in c_1 equals the data in c_2, we put it into vx. for data that are not equal, it iterats over a sequence.
            vx.append(c_2[j])#at the end, this list will give us all the cities repeated in two data sets (college&crime)

for i in vx:# for loop,take every element in vx to run
    if i not in simp:#if any element in vs doesn't exist in simp, if any element is already in simp, it will be added again into simp
        simp.append(i)# will be added into simp.
print(simp)#print simp and check if it is the list we expected to have, clean data

#ynl

['City', 'Washington', 'Gainesville', 'Peoria', 'Bloomington', 'Richmond', 'Cedar Rapids', 'Lafayette', 'Grand Rapids', 'Ann Arbor', 'Minneapolis', 'Syracuse', 'Rochester', 'Utica', 'Portland', 'Pittsburgh', 'Gettysburg', 'York', 'Providence', 'Sioux Falls', 'Provo', 'Harrisonburg', 'Charlottesville', 'Green Bay', 'Madison']

In [77]:
print(vx) #list out this data, "Washitong *10...etc.", too many repated city names listed out, we need to delete the repated names, to clean the data.

['City', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'Gainesville', 'Peoria', 'Bloomington', 'Richmond', 'Cedar Rapids', 'Lafayette', 'Grand Rapids', 'Ann Arbor', 'Minneapolis', 'Syracuse', 'Rochester', 'Rochester', 'Rochester', 'Rochester', 'Syracuse', 'Rochester', 'Rochester', 'Syracuse', 'Utica', 'Syracuse', 'Portland', 'Portland', 'Pittsburgh', 'Gettysburg', 'York', 'Pittsburgh', 'Providence', 'Providence', 'Providence', 'Sioux Falls', 'Provo', 'Harrisonburg', 'Charlottesville', 'Green Bay', 'Madison', 'Rochester', 'Rochester']

In [67]:
lines = []#creat an empty list
with open('college_data.csv', 'r') as readFile: 

    reader = csv.reader(readFile)#read this file
    for row in reader:
        lines.append(row)#every column will be added into lines, which means lines=readerfile

    sample = []#emptey list
    
    for row in lines:#for loop, for every row in "lines"
        k = (row[-1])# read last element in the list, which is "city"
        if k in simp:
            sample.append(row) # if "k"ï¼ˆcity) in "simp",we will put that row(for information,not just city name column anymore) in "sample"

with open('VXtest_1.csv','w') as writeFile:
    writer = csv.writer(writeFile)
    writer.writerows(sample)#write every row in sample/write this file
    
#ynl

In [68]:
#runs same steps again for data"crime_data.csv"
lines = []
with open('crime_data.csv', 'r') as readFile:#

    reader = csv.reader(readFile)#
    for row in reader:
        lines.append(row)#

    sample = []#
    
    for row in lines:#
        k = (row[-1])#
        if k in simp:#
            sample.append(row)

with open('VXtest_2.csv','w') as writeFile:#
    writer = csv.writer(writeFile)#
    writer.writerows(sample)#
    
#ynl

In [69]:
import pandas as pd 
#printed out two data sets for us to check if these two are the lists we wanted to use.  
data1 = pd.read_csv('VXtest_1.csv')
data2 = pd.read_csv('VXtest_2.csv')
print(data1)#
print(".........")
print(data2)#
print(".........")

#ynl

                                               INSTNM  ADM_RATE_ALL  ACTCM25  \
0                                 American University        0.4312     26.0
1                      Catholic University of America        0.6007     22.0
2                        George Washington University        0.3308     27.0
3                               Georgetown University        0.1697     29.0
4                                   Howard University        0.4930     21.0
5                               University of Florida        0.4655     26.0
6                                  Bradley University        0.6694     23.0
7                        Illinois Wesleyan University        0.5838     25.0
8                                     Earlham College        0.6370     26.0
9                                         Coe College        0.6171     23.0
10               University of Louisiana at Lafayette        0.5930     21.0
11                             Cornerstone University        0.6807     21.0
12                   University of Michigan-Ann Arbor        0.3326     28.0
13                University of Minnesota-Twin Cities        0.4455     26.0
14                                   Le Moyne College        0.6190     21.0
15                  Rochester Institute of Technology        0.6016     25.0
16                            University of Rochester        0.3568     29.0
17  St Joseph's College of Nursing at St Joseph's ...        0.4121     21.0
18                          Saint John Fisher College        0.6277     22.0
19  SUNY College of Environmental Science and Fore...        0.5052     23.0
20         SUNY Institute of Technology at Utica-Rome        0.4754     22.0
21                                Syracuse University        0.4949     23.0
22                              Lewis & Clark College        0.6285     26.0
23                                       Reed College        0.4853     28.0
24                         Carnegie Mellon University        0.2549     30.0
25                                 Gettysburg College        0.4163     27.0
26      Pennsylvania State University-Penn State York        0.6488     21.0
27         University of Pittsburgh-Pittsburgh Campus        0.6088     26.0
28                                   Brown University        0.0918     29.0
29                                 Providence College        0.5979     23.0
30                      Rhode Island School of Design        0.2731     24.0
31                                  Augustana College        0.6809     21.0
32                     Brigham Young University-Provo        0.4942     26.0
33                           James Madison University        0.6356     23.0
34                 University of Virginia-Main Campus        0.2999     29.0
35                                     Bellin College        0.5556     22.0
36                    University of Wisconsin-Madison        0.6792     26.0
37                  University of Minnesota-Rochester        0.4455     23.0

    TUITIONFEE_OUT  UGDS_WHITE  UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  UGDS_AIAN  \
0          40649.0      0.5671      0.0640     0.1012      0.0638     0.0018
1          38526.0      0.6311      0.0549     0.1052      0.0313     0.0016
2          47343.0      0.6026      0.0653     0.0739      0.0948     0.0020
3          44805.0      0.5886      0.0638     0.0788      0.0919     0.0014
4          22683.0      0.0134      0.9183     0.0036      0.0130     0.0197
5          28541.0      0.5843      0.0740     0.1902      0.0754     0.0026
6          29664.0      0.7900      0.0616     0.0587      0.0344     0.0025
7          39316.0      0.7380      0.0460     0.0630      0.0460     0.0030
8          41450.0      0.5354      0.1348     0.0581      0.0374     0.0089
9          35730.0      0.7882      0.0406     0.0546      0.0236     0.0022
10         15742.0      0.6842      0.2130     0.0316      0.0193     0.0043
11         24168.0      0.8057      0.1100     0.0457      0.0114     0.0043
12         40392.0      0.6272      0.0436     0.0412      0.1222     0.0016
13         19805.0      0.7147      0.0381     0.0302      0.0858     0.0028
14         30460.0      0.7812      0.0554     0.0569      0.0263     0.0061
15         34424.0      0.6274      0.0516     0.0635      0.0589     0.0021
16         45372.0      0.5361      0.0475     0.0567      0.1052     0.0026
17         19020.0      0.9073      0.0331     0.0364      0.0166     0.0033
18         28430.0      0.8351      0.0424     0.0390      0.0258     0.0020
19         16483.0      0.8725      0.0130     0.0242      0.0272     0.0018
20         16540.0      0.8069      0.0758     0.0554      0.0309     0.0018
21         40458.0      0.5567      0.0894     0.1076      0.0807     0.0071
22         41928.0      0.6479      0.0217     0.0841      0.0605     0.0141
23         46010.0      0.6077      0.0163     0.1081      0.0511     0.0015
24         47642.0      0.3877      0.0519     0.0754      0.2473     0.0005
25         45870.0      0.8175      0.0274     0.0444      0.0143     0.0000
26         20278.0      0.6850      0.0753     0.0721      0.0562     0.0021
27         27106.0      0.7683      0.0546     0.0259      0.0752     0.0004
28         45612.0      0.4327      0.0642     0.1084      0.1233     0.0039
29         43245.0      0.7667      0.0411     0.0675      0.0118     0.0013
30         42932.0      0.3342      0.0249     0.0828      0.1636     0.0015
31         28630.0      0.8712      0.0186     0.0198      0.0087     0.0012
32          4850.0      0.8344      0.0047     0.0554      0.0198     0.0041
33         23654.0      0.7880      0.0399     0.0472      0.0414     0.0015
34         40054.0      0.6070      0.0630     0.0579      0.1224     0.0013
35         20405.0      0.9509      0.0035     0.0070      0.0070     0.0211
36         26653.0      0.7713      0.0215     0.0459      0.0551     0.0022
37         13056.0      0.7966      0.0692     0.0314      0.0566     0.0000

    UGDS_NHPI  UGDS_2MOR  UGDS_NRA  UGDS_UNKN             City
0      0.0004     0.0499    0.0688     0.0829       Washington
1      0.0011     0.0313    0.0481     0.0953       Washington
2      0.0007     0.0330    0.0879     0.0398       Washington
3      0.0008     0.0394    0.1073     0.0281       Washington
4      0.0039     0.0000    0.0280     0.0000       Washington
5      0.0070     0.0282    0.0105     0.0277      Gainesville
6      0.0010     0.0379    0.0085     0.0054           Peoria
7      0.0005     0.0140    0.0490     0.0405      Bloomington
8      0.0000     0.0030    0.1969     0.0256         Richmond
9      0.0000     0.0339    0.0192     0.0376     Cedar Rapids
10     0.0008     0.0158    0.0220     0.0091        Lafayette
11     0.0010     0.0067    0.0152     0.0000     Grand Rapids
12     0.0004     0.0310    0.0667     0.0661        Ann Arbor
13     0.0007     0.0330    0.0873     0.0074      Minneapolis
14     0.0004     0.0229    0.0057     0.0451         Syracuse
15     0.0006     0.0245    0.0510     0.1205        Rochester
16     0.0008     0.0278    0.1507     0.0726        Rochester
17     0.0000     0.0033    0.0000     0.0000         Syracuse
18     0.0010     0.0142    0.0020     0.0383        Rochester
19     0.0006     0.0236    0.0171     0.0201         Syracuse
20     0.0018     0.0187    0.0088     0.0000            Utica
21     0.0005     0.0257    0.0936     0.0387         Syracuse
22     0.0030     0.0076    0.0494     0.1118         Portland
23     0.0000     0.0807    0.0607     0.0740         Portland
24     0.0002     0.0415    0.1414     0.0540       Pittsburgh
25     0.0000     0.0250    0.0246     0.0468       Gettysburg
26     0.0000     0.0212    0.0710     0.0170             York
27     0.0005     0.0287    0.0333     0.0130       Pittsburgh
28     0.0010     0.0537    0.1166     0.0962       Providence
29     0.0018     0.0154    0.0186     0.0758       Providence
30     0.0010     0.0339    0.2369     0.1212       Providence
31     0.0000     0.0161    0.0644     0.0000      Sioux Falls
32     0.0060     0.0310    0.0323     0.0124            Provo
33     0.0018     0.0323    0.0195     0.0282     Harrisonburg
34     0.0003     0.0429    0.0565     0.0486  Charlottesville
35     0.0000     0.0000    0.0000     0.0105        Green Bay
36     0.0012     0.0264    0.0725     0.0038          Madison
37     0.0000     0.0314    0.0042     0.0105        Rochester
.........
                                                  MSA  ViolentCrime  Murder  \
0                                Ann Arbor, MI M.S.A.         319.5     1.9
1                              Bloomington, IL M.S.A.         252.0     0.0
2                             Cedar Rapids, IA M.S.A.         189.5     3.0
3                          Charlottesville, VA M.S.A.         164.6     1.3
4                              Gainesville, GA M.S.A.         188.8     2.6
5                               Gettysburg, PA M.S.A.         135.6     0.0
6                     Grand Rapids-Wyoming, MI M.S.A.         329.0     1.7
7                                Green Bay, WI M.S.A.         196.6     1.3
8                             Harrisonburg, VA M.S.A.         145.8     0.8
9                 Lafayette-West Lafayette, IN M.S.A.         292.0     1.9
10                                 Madison, WI M.S.A.         211.9     2.7
11     Minneapolis-St. Paul-Bloomington, MN-WI M.S.A.         285.2     2.7
12                                  Peoria, IL M.S.A.         358.2     4.5
13                              Pittsburgh, PA M.S.A.         266.3     4.7
14                 Portland-South Portland, ME M.S.A.         134.6     0.8
15                   Providence-Warwick, RI-MA M.S.A.         333.7     2.2
16                              Provo-Orem, UT M.S.A.          71.7     0.3
17                                Richmond, VA M.S.A.         236.5     7.5
18                               Rochester, MN M.S.A.         127.6     0.5
19                               Rochester, NY M.S.A.         280.7     3.8
20                             Sioux Falls, SD M.S.A.         363.7     1.2
21                                Syracuse, NY M.S.A.         284.2     4.1
22                              Utica-Rome, NY M.S.A.         233.6     2.7
23  Washington-Arlington-Alexandria, DC-VA-MD-WV M...         324.1     5.3
24  Washington-Arlington-Alexandria, DC-VA-MD-WV M.D.         356.0     6.0
25                            York-Hanover, PA M.S.A.         217.5     4.3

    Rape  Robbery  AggravatedAssault  PropertyCrime  Burglary   Theft  \
0   57.0     51.4              209.2         1791.9     290.4  1417.4
1   61.8     32.0              158.2         1668.6     322.2  1278.3
2   18.8     43.7              123.9         2350.4     532.3  1681.7
3   35.5     31.5               96.3         1514.5     252.2  1199.2
4   22.2     35.6              128.4         1845.1     373.5  1328.8
5   34.4     13.8               87.5          983.9     243.8   705.7
6   75.1     59.8              192.3         1618.2     301.4  1236.4
7   25.0     24.7              145.7         1453.9     217.8  1177.3
8   36.5     11.4               97.2         1555.7     302.3  1200.9
9   36.0     59.3              194.8         2509.3     503.6  1847.3
10  29.7     46.8              132.7         1956.7     310.1  1580.9
11  40.8     97.1              144.6         2367.5     353.6  1842.4
12  44.8     93.6              215.3         2222.7     497.1  1653.7
13  17.6     76.4              167.6         1782.9     321.6  1389.0
14  24.4     35.6               73.8         1833.7     325.8  1448.0
15  39.1     65.3              227.2         1876.8     385.3  1364.1
16  25.2      7.9               38.3         1551.5     188.1  1275.4
17  25.2     77.6              126.3         2351.7     387.2  1823.2
18  29.0     25.7               72.4         1514.4     307.9  1142.0
19  44.4     82.1              150.4         2107.6     388.3  1609.4
20  57.9     35.3              269.3         2503.3     492.2  1826.7
21  48.0     73.1              159.0         2059.1     383.4  1597.7
22  56.2     38.9              135.8         1983.3     355.5  1558.4
23  27.2    123.2              168.3         1929.2     215.5  1552.2
24  28.1    140.5              181.4         2027.9     220.3  1621.3
25  23.3     64.3              125.6         1551.4     232.6  1255.2

    MotorVehicleTheft State             City
0                84.2    MI        Ann Arbor
1                68.1    IL      Bloomington
2               136.4    IA     Cedar Rapids
3                63.0    VA  Charlottesville
4               142.9    GA      Gainesville
5                34.4    PA       Gettysburg
6                80.4    MI     Grand Rapids
7                58.8    WI        Green Bay
8                52.4    VA     Harrisonburg
9               158.4    IN        Lafayette
10               65.7    WI          Madison
11              171.4    MN      Minneapolis
12               72.0    IL           Peoria
13               72.3    PA       Pittsburgh
14               60.0    ME         Portland
15              127.4    RI       Providence
16               88.0    UT            Provo
17              141.3    VA         Richmond
18               64.5    MN        Rochester
19              109.9    NY        Rochester
20              184.4    SD      Sioux Falls
21               77.9    NY         Syracuse
22               69.4    NY            Utica
23              161.5    DC       Washington
24              186.3    DC       Washington
25               63.6    PA             York
.........

In [72]:
df = pd.read_csv('VXtest_1.csv') #this is the data we filter out (recommanded colleges with required preferences) We get 38 schools in total.
#ynl

In [73]:
df

,INSTNM,ADM_RATE_ALL,ACTCM25,TUITIONFEE_OUT,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,City
0,American University,0.4312,26.0,40649.0,0.5671,0.0640,0.1012,0.0638,0.0018,0.0004,0.0499,0.0688,0.0829,Washington
1,Catholic University of America,0.6007,22.0,38526.0,0.6311,0.0549,0.1052,0.0313,0.0016,0.0011,0.0313,0.0481,0.0953,Washington
2,George Washington University,0.3308,27.0,47343.0,0.6026,0.0653,0.0739,0.0948,0.0020,0.0007,0.0330,0.0879,0.0398,Washington
3,Georgetown University,0.1697,29.0,44805.0,0.5886,0.0638,0.0788,0.0919,0.0014,0.0008,0.0394,0.1073,0.0281,Washington
4,Howard University,0.4930,21.0,22683.0,0.0134,0.9183,0.0036,0.0130,0.0197,0.0039,0.0000,0.0280,0.0000,Washington
5,University of Florida,0.4655,26.0,28541.0,0.5843,0.0740,0.1902,0.0754,0.0026,0.0070,0.0282,0.0105,0.0277,Gainesville
6,Bradley University,0.6694,23.0,29664.0,0.7900,0.0616,0.0587,0.0344,0.0025,0.0010,0.0379,0.0085,0.0054,Peoria
7,Illinois Wesleyan University,0.5838,25.0,39316.0,0.7380,0.0460,0.0630,0.0460,0.0030,0.0005,0.0140,0.0490,0.0405,Bloomington
8,Earlham College,0.6370,26.0,41450.0,0.5354,0.1348,0.0581,0.0374,0.0089,0.0000,0.0030,0.1969,0.0256,Richmond
9,Coe College,0.6171,23.0,35730.0,0.7882,0.0406,0.0546,0.0236,0.0022,0.0000,0.0339,0.0192,0.0376,Cedar Rapids
10,University of Louisiana at Lafayette,0.5930,21.0,15742.0,0.6842,0.2130,0.0316,0.0193,0.0043,0.0008,0.0158,0.0220,0.0091,Lafayette
11,Cornerstone University,0.6807,21.0,24168.0,0.8057,0.1100,0.0457,0.0114,0.0043,0.0010,0.0067,0.0152,0.0000,Grand Rapids
12,University of Michigan-Ann Arbor,0.3326,28.0,40392.0,0.6272,0.0436,0.0412,0.1222,0.0016,0.0004,0.0310,0.0667,0.0661,Ann Arbor
13,University of Minnesota-Twin Cities,0.4455,26.0,19805.0,0.7147,0.0381,0.0302,0.0858,0.0028,0.0007,0.0330,0.0873,0.0074,Minneapolis
14,Le Moyne College,0.6190,21.0,30460.0,0.7812,0.0554,0.0569,0.0263,0.0061,0.0004,0.0229,0.0057,0.0451,Syracuse
15,Rochester Institute of Technology,0.6016,25.0,34424.0,0.6274,0.0516,0.0635,0.0589,0.0021,0.0006,0.0245,0.0510,0.1205,Rochester
16,University of Rochester,0.3568,29.0,45372.0,0.5361,0.0475,0.0567,0.1052,0.0026,0.0008,0.0278,0.1507,0.0726,Rochester
17,St Joseph's College of Nursing at St Joseph's ...,0.4121,21.0,19020.0,0.9073,0.0331,0.0364,0.0166,0.0033,0.0000,0.0033,0.0000,0.0000,Syracuse
18,Saint John Fisher College,0.6277,22.0,28430.0,0.8351,0.0424,0.0390,0.0258,0.0020,0.0010,0.0142,0.0020,0.0383,Rochester
19,SUNY College of Environmental Science and Fore...,0.5052,23.0,16483.0,0.8725,0.0130,0.0242,0.0272,0.0018,0.0006,0.0236,0.0171,0.0201,Syracuse
20,SUNY Institute of Technology at Utica-Rome,0.4754,22.0,16540.0,0.8069,0.0758,0.0554,0.0309,0.0018,0.0018,0.0187,0.0088,0.0000,Utica
21,Syracuse University,0.4949,23.0,40458.0,0.5567,0.0894,0.1076,0.0807,0.0071,0.0005,0.0257,0.0936,0.0387,Syracuse
22,Lewis & Clark College,0.6285,26.0,41928.0,0.6479,0.0217,0.0841,0.0605,0.0141,0.0030,0.0076,0.0494,0.1118,Portland
23,Reed College,0.4853,28.0,46010.0,0.6077,0.0163,0.1081,0.0511,0.0015,0.0000,0.0807,0.0607,0.0740,Portland
24,Carnegie Mellon University,0.2549,30.0,47642.0,0.3877,0.0519,0.0754,0.2473,0.0005,0.0002,0.0415,0.1414,0.0540,Pittsburgh
25,Gettysburg College,0.4163,27.0,45870.0,0.8175,0.0274,0.0444,0.0143,0.0000,0.0000,0.0250,0.0246,0.0468,Gettysburg
26,Pennsylvania State University-Penn State York,0.6488,21.0,20278.0,0.6850,0.0753,0.0721,0.0562,0.0021,0.0000,0.0212,0.0710,0.0170,York
27,University of Pittsburgh-Pittsburgh Campus,0.6088,26.0,27106.0,0.7683,0.0546,0.0259,0.0752,0.0004,0.0005,0.0287,0.0333,0.0130,Pittsburgh
28,Brown University,0.0918,29.0,45612.0,0.4327,0.0642,0.1084,0.1233,0.0039,0.0010,0.0537,0.1166,0.0962,Providence
29,Providence College,0.5979,23.0,43245.0,0.7667,0.0411,0.0675,0.0118,0.0013,0.0018,0.0154,0.0186,0.0758,Providence
30,Rhode Island School of Design,0.2731,24.0,42932.0,0.3342,0.0249,0.0828,0.1636,0.0015,0.0010,0.0339,0.2369,0.1212,Providence
31,Augustana College,0.6809,21.0,28630.0,0.8712,0.0186,0.0198,0.0087,0.0012,0.0000,0.0161,0.0644,0.0000,Sioux Falls
32,Brigham Young University-Provo,0.4942,26.0,4850.0,0.8344,0.0047,0.0554,0.0198,0.0041,0.0060,0.0310,0.0323,0.0124,Provo
33,James Madison University,0.6356,23.0,23654.0,0.7880,0.0399,0.0472,0.0414,0.0015,0.0018,0.0323,0.0195,0.0282,Harrisonburg
34,University of Virginia-Main Campus,0.2999,29.0,40054.0,0.6070,0.0630,0.0579,0.1224,0.0013,0.0003,0.0429,0.0565,0.0486,Charlottesville
35,Bellin College,0.5556,22.0,20405.0,0.9509,0.0035,0.0070,0.0070,0.0211,0.0000,0.0000,0.0000,0.0105,Green Bay
36,University of Wisconsin-Madison,0.6792,26.0,26653.0,0.7713,0.0215,0.0459,0.0551,0.0022,0.0012,0.0264,0.0725,0.0038,Madison
37,University of Minnesota-Rochester,0.4455,23.0,13056.0,0.7966,0.0692,0.0314,0.0566,0.0000,0.0000,0.0314,0.0042,0.0105,Rochester

In [74]:
df = pd.read_csv('VXtest_2.csv')

In [75]:
df

,MSA,ViolentCrime,Murder,Rape,Robbery,AggravatedAssault,PropertyCrime,Burglary,Theft,MotorVehicleTheft,State,City
0,"Ann Arbor, MI M.S.A.",319.5,1.9,57.0,51.4,209.2,1791.9,290.4,1417.4,84.2,MI,Ann Arbor
1,"Bloomington, IL M.S.A.",252.0,0.0,61.8,32.0,158.2,1668.6,322.2,1278.3,68.1,IL,Bloomington
2,"Cedar Rapids, IA M.S.A.",189.5,3.0,18.8,43.7,123.9,2350.4,532.3,1681.7,136.4,IA,Cedar Rapids
3,"Charlottesville, VA M.S.A.",164.6,1.3,35.5,31.5,96.3,1514.5,252.2,1199.2,63.0,VA,Charlottesville
4,"Gainesville, GA M.S.A.",188.8,2.6,22.2,35.6,128.4,1845.1,373.5,1328.8,142.9,GA,Gainesville
5,"Gettysburg, PA M.S.A.",135.6,0.0,34.4,13.8,87.5,983.9,243.8,705.7,34.4,PA,Gettysburg
6,"Grand Rapids-Wyoming, MI M.S.A.",329.0,1.7,75.1,59.8,192.3,1618.2,301.4,1236.4,80.4,MI,Grand Rapids
7,"Green Bay, WI M.S.A.",196.6,1.3,25.0,24.7,145.7,1453.9,217.8,1177.3,58.8,WI,Green Bay
8,"Harrisonburg, VA M.S.A.",145.8,0.8,36.5,11.4,97.2,1555.7,302.3,1200.9,52.4,VA,Harrisonburg
9,"Lafayette-West Lafayette, IN M.S.A.",292.0,1.9,36.0,59.3,194.8,2509.3,503.6,1847.3,158.4,IN,Lafayette
10,"Madison, WI M.S.A.",211.9,2.7,29.7,46.8,132.7,1956.7,310.1,1580.9,65.7,WI,Madison
11,"Minneapolis-St. Paul-Bloomington, MN-WI M.S.A.",285.2,2.7,40.8,97.1,144.6,2367.5,353.6,1842.4,171.4,MN,Minneapolis
12,"Peoria, IL M.S.A.",358.2,4.5,44.8,93.6,215.3,2222.7,497.1,1653.7,72.0,IL,Peoria
13,"Pittsburgh, PA M.S.A.",266.3,4.7,17.6,76.4,167.6,1782.9,321.6,1389.0,72.3,PA,Pittsburgh
14,"Portland-South Portland, ME M.S.A.",134.6,0.8,24.4,35.6,73.8,1833.7,325.8,1448.0,60.0,ME,Portland
15,"Providence-Warwick, RI-MA M.S.A.",333.7,2.2,39.1,65.3,227.2,1876.8,385.3,1364.1,127.4,RI,Providence
16,"Provo-Orem, UT M.S.A.",71.7,0.3,25.2,7.9,38.3,1551.5,188.1,1275.4,88.0,UT,Provo
17,"Richmond, VA M.S.A.",236.5,7.5,25.2,77.6,126.3,2351.7,387.2,1823.2,141.3,VA,Richmond
18,"Rochester, MN M.S.A.",127.6,0.5,29.0,25.7,72.4,1514.4,307.9,1142.0,64.5,MN,Rochester
19,"Rochester, NY M.S.A.",280.7,3.8,44.4,82.1,150.4,2107.6,388.3,1609.4,109.9,NY,Rochester
20,"Sioux Falls, SD M.S.A.",363.7,1.2,57.9,35.3,269.3,2503.3,492.2,1826.7,184.4,SD,Sioux Falls
21,"Syracuse, NY M.S.A.",284.2,4.1,48.0,73.1,159.0,2059.1,383.4,1597.7,77.9,NY,Syracuse
22,"Utica-Rome, NY M.S.A.",233.6,2.7,56.2,38.9,135.8,1983.3,355.5,1558.4,69.4,NY,Utica
23,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",324.1,5.3,27.2,123.2,168.3,1929.2,215.5,1552.2,161.5,DC,Washington
24,"Washington-Arlington-Alexandria, DC-VA-MD-WV M.D.",356.0,6.0,28.1,140.5,181.4,2027.9,220.3,1621.3,186.3,DC,Washington
25,"York-Hanover, PA M.S.A.",217.5,4.3,23.3,64.3,125.6,1551.4,232.6,1255.2,63.6,PA,York